//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.05.11 at 09:58:36 PM CEST
//

package com.osa.spring5.model;

import lombok.Data;

import javax.xml.bind.annotation.XmlElement;

@Data
public class HeartBeatResponse {

    @XmlElement(defaultValue = "true")
    private boolean alive;
}
